[package]
name = "bcdec_rs"
version = "0.2.0"
authors = ["ScanMountGoat <>"]
description = "Safe, no_std, pure Rust port of bcdec"
license = "MIT"
documentation = "https://docs.rs/bcdec_rs"
repository = "https://github.com/ScanMountGoat/image_dds"
edition = "2021"

[dependencies]
