[package]
name = "bcndecode-sys"
version = "0.1.1"
authors = ["ScanMountGoat <>"]
description = "Rust bindings to bcdec"
license = "MIT"
documentation = "https://docs.rs/bcndecode-sys"
repository = "https://github.com/ScanMountGoat/image_dds"
edition = "2021"

[build-dependencies]
cc = "1.0"